api/urls.py
from django.urls import path, include
from api import views
from rest_framework.routers import DefaultRouter

app_name = 'api'

router = DefaultRouter()
router.register(r'account', views.AccountViewSet, basename='account')
router.register(r'post', views.PostViewSet, basename='post')
router.register(r'feed', views.FeedViewSet, basename='feed')
urlpatterns = [
    path('', include(router.urls)),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('feed/', post_comment_create_and_list_view_feed, name='feed-posts-view'),
    path('all/', post_comment_create_and_list_view_all, name='all-post-view'),
    path('liked/', like_unlike, name='like-post-view'),
    path('id/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('id/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('id/<pk>/', post_detail, name='post-detail'),

]

profiles/urls.py
from django.urls import path, include
from .views import *

app_name = 'profiles'

urlpatterns = [

    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('id/<str:slug>/', profile_detail, name='profile-detail'),
    path('id/<str:slug>/subscribe', subscribe_unsubscribe, name='profile-subscribe'),
    path('porfile-all/', profiles_list_view, name='profile-list'),

]

wbTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wbTech import settings
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
]
urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models import Count, Q
from django.template.defaultfilters import slugify
from django.urls import reverse
from image_cropping import ImageRatioField, ImageCropField


class Profile(AbstractUser):
    class Role:
        ordinary_employee = "OE"
        head_of_department = "HOD"
        ROLE_CHOICES = (
            (ordinary_employee, "Рядовой сотрудник"),
            (head_of_department, "Руководитель подразделения"),
        )

    boss = models.ForeignKey(
        "self",
        related_name="slaves",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Начальник",
        default=None,

    )

    first_name = models.CharField(max_length=150, blank=False)
    last_name = models.CharField(max_length=150, blank=False)

    bio = models.TextField(default='no bio…', blank=True, max_length=3000)
    avatar = ImageCropField(default='img/avatars/avatar.png', upload_to='img/avatars/', blank=True)
    cropping = ImageRatioField('avatar', '250x250')
    subs = models.ManyToManyField('self', related_name='my_subscriptions', symmetrical=False, blank=True, default=None,
                                  verbose_name='subscriptions')
    slug = models.SlugField(unique=True, blank=True)

    role = models.CharField(
        "Роль", max_length=30, choices=Role.ROLE_CHOICES, default=Role.ordinary_employee
    )

    def clean(self):
        if not self._state.adding and self.role == Profile.Role.ordinary_employee and self.boss is None:
            raise ValidationError("У рядового сотрудника не может быть пустой начальник")

    def get_absolute_url(self):
        return reverse("profiles:profile-detail", kwargs={"slug": self.slug})

    def get_posts(self):
        return self.posts.all()

    def get_posts_cnt(self):
        return self.posts.all().count()

    def get_subs(self):
        return Profile.objects.filter(subs=self)

    def get_subs_cnt(self):
        return Profile.objects.filter(subs=self).count()

    def get_subscriptions(self):
        return self.subs.all()

    def get_subscriptions_cnt(self):
        return self.subs.all().count()

    def get_all_authors_posts(self):
        return self.posts.all().count()

    def liked_posts(self):
        return self.like_set.all()

    def liked_posts_cnt(self):
        return self.like_set.all().count()

    def get_likes_given_no(self):
        return self.like_set.all().count()

    def get_likes_recieved_no(self):
        return self.posts.all().annotate(liked_count=Count('liked'))[
            0].like_set.all().count() if self.posts.all().count() else 0

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.username) + '-' + str(uuid.uuid4())[:8].replace('-', ''))

        super().save(*args, **kwargs)

profiles/forms.py
from django import forms
from image_cropping import ImageCropWidget

from .models import *


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'cropping', 'first_name', 'last_name', 'bio','slug')
        widgets = {
            'avatar': ImageCropWidget,
        }

profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import ProfileModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required


@login_required
def my_profile_view(request):
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=request.user)
    updated = False
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            updated = True
    return render(request, 'profiles/my-profile.html', {'user': request.user, 'form': form, 'updated': updated})


@login_required
def profile_detail(request, slug):
    profile = get_object_or_404(Profile, slug__iexact=slug)
    if profile == request.user:
        return redirect('profiles:my-profile-view')

    return render(request, 'profiles/profile-detail.html', {'profile': profile})


@login_required
def subscribe_unsubscribe(request, slug):
    user = request.user
    if request.method == 'POST':
        profile = Profile.objects.get(id=request.POST.get('profile_id'))
        if profile in user.get_subscriptions():
            user.subs.remove(profile)
        else:
            user.subs.add(profile)
        user.save()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def profiles_list_view(request):
    profiles = Profile.objects.all()

    return render(request, 'profiles/profile-list.html', {'profiles': profiles})

profiles/templates/profiles/my-profile.html
{% extends 'base.html' %}

{% block title %}
    my user
{% endblock title %}

{% block head %}
    {{ form.media }}

{% endblock head %}
{% block content %}

    <!-- MODAL -->
    <div class="ui modal mymodal">
        <i class="close icon"></i>
        <div class="header">
            Update your Profile
        </div>
        <div class="image content">
            <div class="ui medium image">
                {% load cropping %}
                <img src="{% cropped_thumbnail user "cropping" %}">
            </div>
            <div class="description">

                <div class="ui header">Provide some additional/newest info about you</div>
                <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ form }}
                <button type='submit' class="ui positive right labeled icon button" style="margin-top: 1rem">
                Update
                <i class="checkmark icon"></i>
            </button>
            </form>
            </div>
        </div>
    </div>



    <div class="ui segment">
        {% if updated %}
            <div class="ui green message">Your user has been updated</div>
        {% endif %}
        <div class="ui grid">
            <div class='row'>
                <div class='six wide column'>


                    <img class="ui medium rounded image" src={% cropped_thumbnail user "cropping" %}>
                    <div class="row mt-5">
                        <button class='ui secondary button' id='modal-btn'>Update your user</button>
                    </div>
                </div>
                <div class="ten wide column">
                    <table class="ui table">
                        <tbody>
                        <tr>
                            <td>username</td>
                            <td>{{ user }}</td>
                        </tr>
                         <tr>
                            <td>slug</td>
                            <td>{{ user.slug }}</td>
                        </tr>
                        <tr>
                            <td>first name</td>
                            <td>{{ user.first_name }}</td>
                        </tr>
                        <tr>
                            <td>last name</td>
                            <td>{{ user.last_name }}</td>
                        </tr>
                        <tr>
                            <td>bio</td>
                            <td>{{ user.bio }}</td>
                        </tr>

                        <tr>
                            <td>boss</td>
                            <td><a href="{% url 'profiles:profile-detail' user.boss.slug %}">{{ user.boss.first_name }} {{ user.boss.last_name }}</a></td>

                        </tr>
                        <tr>
                            <td>Number of subscriptions</td>
                            <td>{{ user.get_subscriptions_cnt }}</td>
                        </tr>
                        <tr>
                            <td>All my subscriptions</td>
                            <td>
                                <ul class="no-padding">
                                    {% for sub in user.get_subscriptions %}
                                        <a href="{% url 'profiles:profile-detail' sub.slug %}"><li>{{ sub }}</li></a>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>Number of subscribers</td>
                            <td>{{ user.get_subs_cnt }}</td>
                        </tr>

                        <tr>
                            <td>All my subscribers</td>
                            <td>
                                <ul class="no-padding">
                                    {% for sub in user.get_subs %}

                                         <a href="{% url 'profiles:profile-detail' sub.slug %}"><li>{{ sub }}</li></a>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>number of posts</td>
                            <td>{{ user.get_all_authors_posts }}</td>
                        </tr>
                        <tr>
                            <td>number of likes given</td>
                            <td>{{ user.get_likes_given_no }}</td>
                        </tr>
                        <tr>
                            <td>number of likes received</td>
                            <td>{{ user.get_likes_recieved_no }}</td>
                        </tr>


                        </tbody>
                    </table>


            </div>
            <div class="sixteen wide column">
            <div class="center aligned text container">
                    <h2>Posts:
                    </h2>

                    {% if user.get_posts_cnt %}
                     <div class="ui center aligned text container cards">
                        {% for post in user.get_posts %}
                              <div class="card">
                                <div class="content">
                                  <div class="header">{{ post.title }}</div>
                                </div>
                                <a href="{% url 'posts:post-detail' post.pk %}" class="ui bottom attached button">
                                  <i class="linkify icon"></i>
                                 View post
                                </a>
                              </div>
                        {% endfor %}
                         </div>
                    {% else %}
                        <h1>No posts of this user ...</h1>
                    {% endif %}

                    </div>
                </div>
                </div>
        </div>




    </div>


{% endblock content %}

profiles/templates/profiles/profile-detail.html
{% extends 'base.html' %}

{% block title %}
    profile detail
{% endblock title %}

{% block content %}
    <div class="ui grid">
        <br>
        <div class="row">
            <div class="four wide column">
                {% load cropping %}

                <img class="ui medium rounded image" src="{% cropped_thumbnail profile "cropping" %}">
                <h1>{{ profile.get_full_name }}
                    {% if profile.role == "HOD" %}
                        <a class="ui yellow image label inline-flex">
                            <img src="https://semantic-ui.com/images/avatar/small/christian.jpg">Начальник</a>
                    {% endif %}
                </h1>

                <div class="ui vertical fluid menu">
                    <div class="item">
                        Posts
                        <div class="ui label">{{ profile.get_posts_cnt }}</div>
                    </div>
                    <div class="item">
                        Likes given
                        <div class="ui label">{{ profile.get_likes_given_no }}</div>
                    </div>
                    <div class="item">
                        Likes received
                        <div class="ui label">{{ profile.get_likes_recieved_no }}</div>
                    </div>
                    <div class="item">
                        Subs
                        <div class="ui label">{{ profile.get_subs_cnt }}</div>
                    </div>
                </div>

                <form action="{% url 'profiles:profile-subscribe' profile.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_id" value={{ profile.id }}>
                    {% if profile.role == "HOD" %}
                        <button class="ui button disabled fluid">Unfollow</button>
                    {% elif profile in request.user.get_subscriptions %}
                        <button class="ui button fluid">Unfollow</button>
                    {% else %}
                        <button class="ui button blue fluid">Follow</button>
                    {% endif %}
                </form>
            </div>
            <div class="twelve wide column">
                {% if profile.get_posts_cnt %}
                    <div class="ui cards">
                        {% for post in profile.get_posts %}
                            <div class="card">
                                <div class="content">
                                    <div class="header">{{ post.title }}</div>

                                </div>

                                <a href="{% url 'posts:post-detail' post.pk %}" class="ui bottom attached button">
                                    <i class="linkify icon"></i>
                                    View post
                                </a>
                            </div>

                        {% endfor %}
                    </div>
                {% else %}
                    <h1>No posts of this user ...</h1>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

profiles/templates/profiles/profile-list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    {% for profile in profiles %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{profile.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{profile}}</h3>
                        <p>{{profile.bio}}</p>
                        <a href={{profile.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>

                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}