accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = 'reg'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

api/urls.py
from django.urls import path, include
from api import views
from rest_framework.routers import DefaultRouter

app_name = 'api'

router = DefaultRouter()
router.register(r'account', views.AccountViewSet, basename='account')
router.register(r'post', views.PostViewSet, basename='post')
router.register(r'feed', views.FeedViewSet, basename='feed')
urlpatterns = [
    path('', include(router.urls)),
]

wbTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wbTech import settings
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
]
urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
    home
{% endblock title %}

{% block head %}
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no">
    <meta name="description" content="Semantic-UI-Forest, collection of design, themes and templates for Semantic-UI.">
    <meta name="keywords" content="Semantic-UI, Theme, Design, Template">
    <meta name="author" content="PPType">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
          type="text/css">
    <style type="text/css">
        body {
            -webkit-font-smoothing: antialiased;
            -moz-font-smoothing: grayscale;
        }
    </style>
{% endblock head %}

{% block content %}
    <div class="ui tablet computer only padded grid" style="margin-top:5rem!important">
    <div class="ui center aligned text container">
        <h1 class="ui huge header">Социальная сеть для компании</h1>

        <p class="lead">Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.<br>
           Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
        </p>
        <a href="{{ path_to_posts }}">
            <div class="ui huge teal button ">Перейти в ленту<i class="right arrow icon"></i></div>
        </a>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        <script>
            $(document).ready(function() {
            $(".ui.toggle.button").click(function () {
                $(".mobile.only.grid .ui.vertical.menu").toggle(100);
            });
        });
    </script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i["GoogleAnalyticsObject"] = r;
            (i[r] =
                i[r] ||
                function () {
                    (i[r].q = i[r].q || []).push(arguments);
                }),
                (i[r].l = 1 * new Date());
            (a = s.createElement(o)), (m = s.getElementsByTagName(o)[0]);
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m);
        })(window, document, "script", "//www.google-analytics.com/analytics.js", "ga");

        ga("create", "UA-87734989-1", "auto");
        ga("send", "pageview");
    </script>

{% endblock scripts %}

templates/main/navbar.html
<div class="ui inverted menu nav mr-1 ml-1 mb-7">
    <div class="ui container">
        <a href="{{ path_to_home }}" class="{% if request.path == path_to_home %}active{% endif %} item">
            <h3>wb — Tech</h3>
        </a>
        {% if request.user.is_authenticated %}
            <a href="{{ path_to_posts }}" class="{% if request.path == path_to_posts %}active{% endif %} item">
                <h4>
                   Feed
                </h4>
            </a>
        {% endif %}

        <div class="right menu">
            {% if request.user.is_authenticated %}
                <div class="item">
                    <div class="ui floating dropdown icon button teal"> Global content
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a href="{{ path_to_all_profiles }}"
                               class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                                All Profiles
                            </a>
                            <a href="{{ path_to_all_posts }}"
                               class="{% if request.path == path_to_all_posts %}active{% endif %} item">
                                All Posts
                            </a>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <form action="" method="GET">
                        <div class="ui action left icon input">
                            <input class="prompt" type="text" name='q' placeholder="User or post...">
                            <i class="search icon"></i>
                            <button type='submit' class="ui button">Search</button>
                        </div>
                    </form>
                </div>

                <a href="{{ path_to_my_profile }}"
                   class="{% if request.path == path_to_my_profile %}active{% endif %} item">
{#                    <img class="ui avatar image" src= {{ picture.url }}> &nbsp;#}
                    {{ request.user }}
                </a>

                <a href="{% url 'logout' %}" class="ui item">
                    Logout
                </a>
            {% else %}
                <a href="{% url 'reg:signup' %}" class="ui item">
                    Registration
                </a>
                <a href="{% url 'login' %}" class="ui item">
                    Login
                </a>
            {% endif %}
        </div>
    </div>
</div>