api/urls.py
from django.urls import path, include
from api import views
from rest_framework.routers import DefaultRouter

app_name = 'api'

router = DefaultRouter()
router.register(r'account', views.AccountViewSet, basename='account')
router.register(r'post', views.PostViewSet, basename='post')
router.register(r'feed', views.FeedViewSet, basename='feed')
urlpatterns = [
    path('', include(router.urls)),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('feed/', post_comment_create_and_list_view_feed, name='feed-posts-view'),
    path('all/', post_comment_create_and_list_view_all, name='all-post-view'),
    path('liked/', like_unlike, name='like-post-view'),
    path('id/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('id/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('id/<pk>/', post_detail, name='post-detail'),

]

profiles/urls.py
from django.urls import path, include
from .views import *

app_name = 'profiles'

urlpatterns = [

    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('id/<str:slug>/', profile_detail, name='profile-detail'),
    path('id/<str:slug>/subscribe', subscribe_unsubscribe, name='profile-subscribe'),
    path('porfile-all/', profiles_list_view, name='profile-list'),

]

wbTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wbTech import settings
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
]
urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

{% url 'home-view' as path_to_home %}
{% url 'posts:feed-posts-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:profile-list' as path_to_all_profiles %}
{% url 'posts:all-post-view' as path_to_all_posts %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %}
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
     {% block head %}
     {% endblock head %}

    <title> wbTech - {% block title %}{% endblock title %} </title>
  </head>
  <body>
    {% include 'main/navbar.html' %}
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}

   <!--Custom js ADD-->
   <script type="text/javascript" src={% static 'js/main.js' %}></script>
`
  </body>
</html>