api/urls.py
from django.urls import path, include
from api import views
from rest_framework.routers import DefaultRouter

app_name = 'api'

router = DefaultRouter()
router.register(r'account', views.AccountViewSet, basename='account')
router.register(r'post', views.PostViewSet, basename='post')
router.register(r'feed', views.FeedViewSet, basename='feed')
urlpatterns = [
    path('', include(router.urls)),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('feed/', post_comment_create_and_list_view_feed, name='feed-posts-view'),
    path('all/', post_comment_create_and_list_view_all, name='all-post-view'),
    path('liked/', like_unlike, name='like-post-view'),
    path('id/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('id/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('id/<pk>/', post_detail, name='post-detail'),

]

profiles/urls.py
from django.urls import path, include
from .views import *

app_name = 'profiles'

urlpatterns = [

    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('id/<str:slug>/', profile_detail, name='profile-detail'),
    path('id/<str:slug>/subscribe', subscribe_unsubscribe, name='profile-subscribe'),
    path('porfile-all/', profiles_list_view, name='profile-list'),

]

wbTech/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from wbTech import settings
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
]
urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile


class Post(models.Model):
    title = models.CharField(max_length=200, default='')
    content = models.TextField()
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(f'{self.title} - {self.author.username}')

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}"

posts/forms.py
from django import forms
from .models import *
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')
        widgets = {
            'content': SummernoteWidget(),
        }


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='Comment:', widget=forms.TextInput(attrs={'placeholder': 'Add a comment '}))

    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import *
from .forms import *
from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import connection


def post_mixin(request, only_feed: bool):
    user = request.user
    if only_feed:
        cursor = connection.cursor()
        cursor.execute(
            f'''
            select * from posts_post post join profiles_profile_subs 
            on to_profile_id = post.author_id 
            where from_profile_id = {request.user.id}
            ''')
        current_id = [obj[0] for obj in cursor.fetchall()]
        posts = Post.objects.filter(pk__in=current_id) | Post.objects.filter(author__in=[request.user.boss, request.user])
    else:
        posts = Post.objects.all()
    post_form = PostModelForm()
    comment_form = CommentModelForm()
    post_added = False

    if 'submit_post_form' in request.POST:
        post_form = PostModelForm(request.POST, request.FILES)
        if post_form.is_valid():
            ins = post_form.save(commit=False)
            ins.author = user
            ins.save()
            post_added = True
            # return redirect(request.META.get('HTTP_REFERER'), {'post_added':True})

    if 'submit_comment_form' in request.POST:
        comment_form = CommentModelForm(request.POST or None)
        if comment_form.is_valid():
            ins = comment_form.save(commit=False)
            ins.user = user
            ins.post = Post.objects.get(id=request.POST.get('post_id'))
            ins.save()
            print(request.META)
            print(request.path)
            return redirect(request.META.get('HTTP_REFERER'))

    return render(request, 'posts/main.html',
                  {'posts': posts, 'post_form': post_form, 'comment_form': comment_form, 'post_added': post_added,
                   'user': user})


@login_required
def post_comment_create_and_list_view_feed(request):
    return post_mixin(request, True)


@login_required
def post_comment_create_and_list_view_all(request):
    return post_mixin(request, False)


@login_required
def like_unlike(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = Like.objects.get_or_create(user=user, post_id=post_id)
        if not created:
            post_obj.save()
            like.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def post_detail(request, pk):
    comment_form = CommentModelForm()
    post = get_object_or_404(Post, pk__iexact=pk)

    return render(request, 'posts/post-detail.html', {'post': post, 'comment_form': comment_form})


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:all-post-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        if not post.author == self.request.user:
            messages.waring(self.request, 'Authentication error')
        return post


class PostUpdateView(UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:all-post-view')

    def form_valid(self, form):
        user = self.request.user
        if form.instance.author == user:
            return super().form_valid(form)
        form.add_error(None, 'Authentication error')
        return super().form_invalid(form)

posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
delete post
{% endblock title %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class='ui negative message'>
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not messages %}
        <div class="ui segment">
            <h3>Delete post?</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete the post?</p>
                <button type='submit' class="ui red button">Submit</button>
            </form>
        </div>
    {% endif %}

{% endblock content %}

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}posts{% endblock title %}

{% block head %}
    {% load cropping %}
{% endblock head %}
{% block content %}
    <!-- MODAL -->
    <div class="ui modal mymodal">
        <i class="close icon"></i>
        <div class="header">
            Add new post
        </div>
        <div class="content">
            <div class="description">
                <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                    {% csrf_token %}
                    <label>Title:</label>
                    {{ post_form.title }}
                    <label>Content:</label>
                    <div>


                        {{ post_form.content }}
                    </div>
                    <button type='submit' name="submit_post_form" class="ui positive button w-full mt-5">Send</button>
                </form>

            </div>
        </div>
    </div>


    <div class="ui grid">
        <div class="thirteen wide column">
        {% if post_added %}
            <div class="ui green message">Post has been added</div>
        {% endif %}
            {% for post in posts %}

                <div class="ui fluid card">
                    <div class="content">
                        <div class="right floated meta">
                            <div class="ui grid">
                                <div class="row">
                                    {% if user == post.author %}
                                        <a href="{% url 'posts:post-update' post.pk %}">
                                            <button class="ui button bwhite-lg ">Update</button>
                                        </a>
                                        <a href="{% url 'posts:post-delete' post.pk %}">
                                            <button class="ui button bwhite-lg ">Delete</button>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                        <img class="ui avatar image" src="{% cropped_thumbnail post.author "cropping" %}">
                        <a href="{% url 'profiles:profile-detail' post.author.slug %}"><span> {{ post.author.get_full_name }}</a> - {{ post.created|timesince }} ago</span>

                    </div>

                    <div class="content">
                        <a href="{% url 'posts:post-detail' post.pk %}" style="text-decoration: none; color: #000;"><h3 style=" text-align: left;">{{post.title}}</h3></a>
                        <p> {{ post.content|safe }} </p>
                        <div class="right floated">


                            <form action="{% url 'posts:like-post-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{ post.id }}>
                                {% if profile not in post.liked.all %}


                                    <div class="ui labeled button" tabindex="0">
                                        <button type="submit"
                                                style="background: transparent; border: none !important; font-size:0;">
                                            <div class="ui red button">
                                                <i class="heart icon mrg-none"></i>
                                            </div>
                                            <a class="ui basic red left pointing label">
                                                {{ post.num_likes }}
                                            </a>
                                        </button>
                                    </div>

                                {% else %}
                                    <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                                    </button>
                                    <span> {{ post.num_likes }} likes</span>
                                {% endif %}
                            </form>
                        </div>
                        <i class="comment icon"></i>
                        <span> {{ post.num_comments }} comments</span>
                    </div>
                    <div class="extra content">
                        <div class="mb-5">

                        </div>
                        {% if post.comment_set.all %}
                            <button class="cmt_btn ui button mb-5">show comments</button>
                        {% endif %}
                        <div class="comment-box">
                            {% if post.comment_set.all %}

                                {% for comment in post.comment_set.all %}

                                    <div class="ui segment mb-5">
                                        <img class="ui avatar image" src="{% cropped_thumbnail comment.user "cropping" %}">
                                        <a href="{% url 'profiles:profile-detail' comment.user.slug %}">{{ comment.user.get_full_name }}</a><span>

                                        <div class='mt-5'>{{ comment.body }}</div>
                                    </div>

                                {% endfor %}
                            {% endif %}
                        </div>

                        <form action="" method="POST" class='ui fluid form'>
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{ post.id }}>
                            {{ comment_form }}
                            <button type="submit" name="submit_comment_form" class="ui primary button mt-5 w-full">
                                Send
                            </button>
                        </form>
                    </div>
                </div>


            {% endfor %}
        </div>
        <div class="three wide column">

            <button class="ui green button fluid mt-5" id='modal-btn'>Add new post</button>



        </div>
    </div>
{% endblock content %}

{% block scripts %}

    <script>
        $(document).ready(function () {
            let display = false
            $(".cmt_btn").click(function () {
                if (display === false) {
                    $(this).next(".comment-box").show("slow");
                    display = true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display = false
                }
            });
        });

    </script>

{% endblock scripts %}

posts/templates/posts/post-detail.html
{% extends 'base.html' %}

{% block head %}
    {% load cropping %}
{% endblock head %}

{% block content %}

<div class="ui grid">
<div class="two wide column">

            <a href="{{request.META.HTTP_REFERER}}"><button class="ui button fluid mt-5" >Back</button></a>

        </div>
        <div class="fourteen wide column">


                <div class="ui fluid card">
                    <div class="content">
                        <div class="right floated meta">
                            <div class="ui grid">
                                <div class="row">
                                    {% if user == post.author %}
                                        <a href="{% url 'posts:post-update' post.pk %}">
                                            <button class="ui button bwhite-lg ">Update</button>
                                        </a>
                                        <a href="{% url 'posts:post-delete' post.pk %}">
                                            <button class="ui button bwhite-lg ">Delete</button>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                        <img class="ui avatar image" src="{% cropped_thumbnail post.author "cropping" %}">

                        <a href="{% url 'profiles:profile-detail' post.author.slug %}"><span> {{ post.author.get_full_name }}</a> - {{ post.created|timesince }} ago</span>
                    </div>

                    <div class="content">
                        <h3 style=" text-align: left;">{{post.title}}</h3>
                        <p> {{ post.content|safe }} </p>
                        <div class="right floated">


                            <form action="{% url 'posts:like-post-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{ post.id }}>
                                {% if profile not in post.liked.all %}


                                    <div class="ui labeled button" tabindex="0">
                                        <button type="submit"
                                                style="background: transparent; border: none !important; font-size:0;">
                                            <div class="ui red button">
                                                <i class="heart icon mrg-none"></i>
                                            </div>
                                            <a class="ui basic red left pointing label">
                                                {{ post.num_likes }}
                                            </a>
                                        </button>
                                    </div>

                                {% else %}
                                    <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                                    </button>
                                    <span> {{ post.num_likes }} likes</span>
                                {% endif %}
                            </form>
                        </div>
                        <i class="comment icon"></i>
                        <span> {{ post.num_comments }} comments</span>
                    </div>
                    <div class="extra content">
                        <div class="mb-5">

                        </div>
                        {% if post.comment_set.all %}
                            <button class="cmt_btn ui button mb-5">show comments</button>
                        {% endif %}
                        <div class="comment-box">
                            {% if post.comment_set.all %}

                                {% for comment in post.comment_set.all %}

                                    <div class="ui segment mb-5">
                                        <img class="ui avatar image" src="{% cropped_thumbnail comment.user "cropping" %}">
                                        <a href="{% url 'profiles:profile-detail' comment.user.slug %}">{{ comment.user.get_full_name }}</a><span>
                                        <div class='mt-5'>{{ comment.body }}</div>
                                    </div>

                                {% endfor %}
                            {% endif %}
                        </div>

                        <form action="{% url 'posts:all-post-view' %}" method="POST" class='ui fluid form'>
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{ post.id }}>
                            {{ comment_form }}
                            <button type="submit" name="submit_comment_form" class="ui primary button mt-5 w-full">
                                Send
                            </button>
                        </form>
                    </div>
                </div>



        </div>

    </div>
{% endblock content %}
{% block scripts %}

    <script>
        $(document).ready(function () {
            let display = false
            $(".cmt_btn").click(function () {
                if (display === false) {
                    $(this).next(".comment-box").show("slow");
                    display = true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display = false
                }
            });
        });

    </script>

{% endblock scripts %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
update post
{% endblock title %}

{% block content %}
    <div class='ui segment'>
        <h3>Update post</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button type='submit' class="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}